default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password:
  socket: /var/lib/mysql/mysql.sock

development:
  <<: *default
  database: ex_controller_development

test:
  <<: *default
  database: ex_controller_test

production:
  <<: *default
  database: ex_controller_production
  username: ex_controller
  password: <%= ENV['EX_CONTROLLER_DATABASE_PASSWORD'] %>
